name: Java CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build
      run: mvn clean install
    - name: Restart App
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
         cd /home/ubuntu

         echo "Stopping old app..."
         PID=$(ps aux | grep demo-1.0.jar | grep -v grep | awk '{print $2}')
         if [ -n "$PID" ]; then
            kill -9 $PID
         fi

         echo "Starting new app..."
         nohup java -jar demo-1.0.jar > app.log 2>&1 