name: Java CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build
      run: mvn clean install

    - name: Remove old JAR
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: rm -f /home/ubuntu/demo-1.0.jar

    - name: Copy new JAR
      uses: appleboy/scp-action@v0.1.7
      with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "target/demo-1.0.jar"
          target: "/home/ubuntu/"
          overwrite: true

    - name: Restart App
      uses: appleboy/ssh-action@v1.0.0
      with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu
            pkill -f demo-1.0.jar || true
            nohup java -Xms128m -Xmx256m -jar demo-1.0.jar > app.log 2>&1 &
            ps aux | grep java
